### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by tzanio** [LLNL/radiuss#29]
First, I have to say that the website looks great. Really nice job! 🎉 

Here are a few small suggestions after a brief look:

- Can we support full search in https://software.llnl.gov/radiuss/projects? Searching by tag is great, but it will be also nice if we can search directly for e.g. `hypre`

- It will be nice to offer groupings and/or different orderings of the projects (e.g. by type, stars, etc.)

- "maching-learning" → "machine-learning" (in https://software.llnl.gov/radiuss/projects/)

- "vizualization" → "visualization" (in https://software.llnl.gov/radiuss/about/)

- There is an extra `->` at the end of https://software.llnl.gov/radiuss/about/

**Comment by vsoch** [comment]
hey @tzanio thank you for this feedback! I will have a PR in for you shortly that can address most of these points - will ping you there in a bit!

**Comment by vsoch** [comment]
Addressed in https://github.com/LLNL/radiuss/pull/33.
