### ISSUE TITLE
RAJA & hypre avatars

### ISSUE THREAD

**Issue by hauten** [LLNL/radiuss#31]
https://software.llnl.gov/radiuss/projects/

1. RAJA avatar exists in the right place with the right name (https://github.com/LLNL/radiuss/blob/main/assets/img/custom/avatars/llnl-raja.png), but the generic LLNL open source logo appears instead.
2. hypre avatar is too large and only shows the "H" (although it does look cool and is perhaps intended). I wasn't sure where the image file resides, unless it's pulled in from the repo directly. A smaller sized file is here, if you want it: https://github.com/LLNL/llnl.github.io/blob/main/assets/images/logos/hypre-space/hypre.png

**Comment by vsoch** [comment]
This is fixed with https://github.com/LLNL/radiuss/pull/30. The hypre avatar reflects their org logo, so I think we can leave until someone from the team requests it to be changed. Thank you @hauten !
